name: RPM Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build RPM package
        id: rpm
        uses: naveenrajm7/rpmbuild@master
        with:
          spec_file: nimf.spec
          additional_repos: >-
            [
              "https://github.com/kanglib/3beol-libhangul/releases/download/libhangul-0.1.0-28/libhangul-0.1.0-28.el7.x86_64.rpm",
              "https://github.com/kanglib/3beol-libhangul/releases/download/libhangul-0.1.0-28/libhangul-devel-0.1.0-28.el7.x86_64.rpm"
            ]

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Binary RPM
          path: ${{ steps.rpm.outputs.rpm_dir_path }}
